### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by s1lence16** [Ezzpify/FindLowDigAccounts#27]
the program gives an error

**Comment by songexile** [comment]
Hey, I believe this program doesn't work anymore and is outdated, these days you can't get accounts with this method.

**Comment by wakech1337** [comment]
what is the  method dm me on discord :𝓓𝓪𝓷𝓴𝓸 ;]#0125

**Comment by TheMasterAcosta** [comment]
> > Hey, I believe this program doesn't work anymore and is outdated, these days you can't get accounts with this method.
> 
> i had a method to recover accounts
do you have the method ?, I have another alternative to this program

**Comment by tarcsi** [comment]
I have successfully fixed lowdig, add me if you want it tarcseh#3400

**Comment by tarcsi** [comment]
if y'all want a fixed version, I've forked this project, you can check it out on my github profile

**Comment by deleteduser2117** [comment]
> if y'all want a fixed version, I've forked this project, you can check it out on my github profile

I get error on startup and lowdig crashes

Unhandled Exception: Unhandled Exception: Unhandled Exception: System.Threading.SemaphoreFullException: Adding the specified count to the semaphore would cause it to exceed its maximum count.
at System.Threading.Semaphore.Release(Int32 releaseCount)
at System.Threading.Semaphore.Release()
at LowDig.Session.ParseResponse(Object o, DownloadStringCompletedEventArgs e, String steamId)
at LowDig.Session.<>c__DisplayClass11_0.b__0(Object sender, DownloadStringCompletedEventArgs e)
at System.Net.WebClient.OnDownloadStringCompleted(DownloadStringCompletedEventArgs e)
at System.Net.WebClient.DownloadStringOperationCompleted(Object arg)
at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Can you repair it?
Thanks
